var dir_e5904cdd2526abf3e4936699df5386dd =
[
    [ "EGM9615.h", "EGM9615_8h_source.html", null ],
    [ "GeomagnetismHeader.h", "GeomagnetismHeader_8h_source.html", null ],
    [ "GeomagnetismLibrary.c", "GeomagnetismLibrary_8c_source.html", null ],
    [ "icons.cpp", "wmm__pi_2src_2icons_8cpp_source.html", null ],
    [ "icons.h", "wmm__pi_2src_2icons_8h_source.html", null ],
    [ "json_defs.h", "wmm__pi_2src_2json__defs_8h_source.html", null ],
    [ "jsonreader.cpp", "wmm__pi_2src_2jsonreader_8cpp_source.html", null ],
    [ "jsonreader.h", "wmm__pi_2src_2jsonreader_8h_source.html", null ],
    [ "jsonval.cpp", "wmm__pi_2src_2jsonval_8cpp_source.html", null ],
    [ "jsonval.h", "wmm__pi_2src_2jsonval_8h_source.html", null ],
    [ "jsonwriter.cpp", "wmm__pi_2src_2jsonwriter_8cpp_source.html", null ],
    [ "jsonwriter.h", "wmm__pi_2src_2jsonwriter_8h_source.html", null ],
    [ "linmath.h", "wmm__pi_2src_2linmath_8h_source.html", null ],
    [ "MagneticPlotMap.cpp", "MagneticPlotMap_8cpp_source.html", null ],
    [ "MagneticPlotMap.h", "MagneticPlotMap_8h_source.html", null ],
    [ "pi_ocpndc.cpp", "wmm__pi_2src_2pi__ocpndc_8cpp_source.html", null ],
    [ "pi_ocpndc.h", "wmm__pi_2src_2pi__ocpndc_8h_source.html", null ],
    [ "pi_shaders.cpp", "wmm__pi_2src_2pi__shaders_8cpp_source.html", null ],
    [ "pi_shaders.h", "wmm__pi_2src_2pi__shaders_8h_source.html", null ],
    [ "pi_TexFont.cpp", "wmm__pi_2src_2pi__TexFont_8cpp_source.html", null ],
    [ "pi_TexFont.h", "wmm__pi_2src_2pi__TexFont_8h_source.html", null ],
    [ "wmm_pi.cpp", "wmm__pi_8cpp_source.html", null ],
    [ "wmm_pi.h", "wmm__pi_8h_source.html", null ],
    [ "WmmUIDialog.cpp", "WmmUIDialog_8cpp_source.html", null ],
    [ "WmmUIDialog.h", "WmmUIDialog_8h_source.html", null ]
];