var dir_8907df15be1e56c6854f77d93ab99015 =
[
    [ "altitude.cpp", "altitude_8cpp_source.html", null ],
    [ "altitude.h", "altitude_8h_source.html", null ],
    [ "baro_history.cpp", "baro__history_8cpp_source.html", null ],
    [ "baro_history.h", "baro__history_8h_source.html", null ],
    [ "clock.cpp", "clock_8cpp_source.html", null ],
    [ "clock.h", "clock_8h_source.html", null ],
    [ "compass.cpp", "plugins_2dashboard__pi_2src_2compass_8cpp_source.html", null ],
    [ "compass.h", "plugins_2dashboard__pi_2src_2compass_8h_source.html", null ],
    [ "dashboard_pi.cpp", "dashboard__pi_8cpp_source.html", null ],
    [ "dashboard_pi.h", "dashboard__pi_8h_source.html", null ],
    [ "depth.cpp", "depth_8cpp_source.html", null ],
    [ "depth.h", "depth_8h_source.html", null ],
    [ "dial.cpp", "dial_8cpp_source.html", null ],
    [ "dial.h", "dial_8h_source.html", null ],
    [ "from_ownship.cpp", "from__ownship_8cpp_source.html", null ],
    [ "from_ownship.h", "from__ownship_8h_source.html", null ],
    [ "gps.cpp", "gps_8cpp_source.html", null ],
    [ "gps.h", "gps_8h_source.html", null ],
    [ "icons.cpp", "dashboard__pi_2src_2icons_8cpp_source.html", null ],
    [ "icons.h", "dashboard__pi_2src_2icons_8h_source.html", null ],
    [ "iirfilter.cpp", "iirfilter_8cpp_source.html", null ],
    [ "iirfilter.h", "iirfilter_8h_source.html", null ],
    [ "instrument.cpp", "instrument_8cpp_source.html", null ],
    [ "instrument.h", "instrument_8h_source.html", null ],
    [ "rudder_angle.cpp", "rudder__angle_8cpp_source.html", null ],
    [ "rudder_angle.h", "rudder__angle_8h_source.html", null ],
    [ "speedometer.cpp", "speedometer_8cpp_source.html", null ],
    [ "speedometer.h", "speedometer_8h_source.html", null ],
    [ "wind.cpp", "wind_8cpp_source.html", null ],
    [ "wind.h", "wind_8h_source.html", null ],
    [ "wind_history.cpp", "wind__history_8cpp_source.html", null ],
    [ "wind_history.h", "wind__history_8h_source.html", null ]
];